name: flutter_badge_controller
description: "A simple Flutter plugin to manage app icon badge (set, clear) for Android and iOS."
version: 0.0.1
homepage: https://github.com/ihdatech/flutter_badge_controller
repository: https://github.com/ihdatech/flutter_badge_controller
topics:
  - badge
  - app-badge
  - icon-badge
  - flutter
  - android
  - ios
  - notification
  - flutter-plugin

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_badge_controller
        pluginClass: FlutterBadgeControllerPlugin
      ios:
        pluginClass: FlutterBadgeControllerPlugin
